name: Create Submission Bundle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: NuGet/setup-nuget@v1

      - name: Restore dependencies
        run: nuget restore OuterZone.sln

      - name: Build the solution
        run: msbuild OuterZone.sln

      - name: Checkout the wiki
        uses: actions/checkout@v2
        with:
          repository: Benjamin-Davies/OuterZone.wiki.git
          ref: master
          path: wiki/
      
      - name: Install pandoc
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install pandoc miktex

      - name: Compile wiki
        run: pandoc wiki/*.md -t pdf
