name: Create Submission Bundle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: NuGet/setup-nuget@v1

      - name: Restore dependencies
        run: nuget restore OuterZone.sln

      - name: Build the solutioln
        run: msbuild OuterZone.sln
